module.exports = {
  data_member: [
    {
      name: "Wahyu Saputra",
      nickName: "Wahyu",
      address: "A1 No. 11",
      position: "Ketua",
      img: "https://i.ibb.co.com/FB95CCn/S10122-A-019699-copy-Wahyu-Saputra.jpg",
      email: "-",
      phone: "082297777934",
      group: "Pengurus Inti",
      order: 0,
    },
    {
      name: "Gugun",
      nickName: "Ugun",
      address: "I2 No. 09",
      position: "Wakil Ketua",
      img: "https://i.ibb.co.com/TPDzm8z/IMG-20191015-WA0044-Ugun-Merdekawati.jpg",
      email: "ugunmerdekawati@gmail.com",
      phone: "082121144675",
      group: "Pengurus Inti",
      order: 0,
    },
    {
      name: "Wisnu Adi Wardhana",
      nickName: "NU",
      address: "B5 No. 21",
      position: "Sekretaris",
      img: "https://i.ibb.co.com/d5dg2SY/Whats-App-Image-2023-10-17-at-6-27-58-PM.webp",
      email: "adiwardhanawisnu@gmail.com",
      phone: "081298698252",
      group: "Pengurus Inti",
      order: 0,
    },
    {
      name: "Hamdan Patra Alam",
      nickName: "Patra",
      address: "C2 No. 10",
      position: "Bendahara I",
      img: "https://i.ibb.co.com/LvXnQqb/image-2.png",
      email: "patraalam@gmail.com",
      phone: "08112348678",
      group: "Pengurus Inti",
      order: 0,
    },
    {
      name: "Anas Saepuloh",
      nickName: "Anas",
      address: "I2 No. 16",
      position: "Bendahara II",
      img: "https://i.ibb.co.com/cQD9gdv/IMG-20241231-WA0003.jpg",
      email: "anassaepuloh0@gmail.com",
      phone: "08881681714",
      group: "Pengurus Inti",
      order: 0,
    },
    {
      name: "Rizky Adha Pratama",
      nickName: "Rizky",
      phone: "089668354553",
      email: "prizkyadha@gmail.com",
      address: "B5 No. 13",
      position: "Ketua RT 1 (Sementara)",
      img: "https://i.ibb.co.com/G0MWthV/IMG-20250101-WA0015.jpg",
      group: "Struktural",
      order: 1,
    },
    {
      name: "Dikdik Sudrajat",
      nickName: "Dikdik",
      phone: "082219534978",
      email: "alamsyahrafa64@gmail.com",
      address: "D2 No. 10",
      position: "Ketua RT 02 (Sementara)",
      img: "https://i.ibb.co.com/GxXynjw/Whats-App-Image-2025-01-07-at-6-11-41-AM.jpg",
      group: "Struktural",
      order: 1,
    },
    {
      name: "Luckyyy Nugraha",
      nickName: "Uki",
      address: "E2 No. 02",
      position: "Koordinator Blok 3 (E-F)",
      img: "https://i.ibb.co.com/v1Dy6Gn/IMG-tne5o1-Lucky-Nugraha.jpg",
      email: "luckynugraha94@gmail.com",
      phone: "08978425093",
      group: "Struktural",
      order: 1,
    },
    {
      name: "Agus Susanto",
      nickName: "Agus",
      address: "I3 No. 15",
      position: "Ketua RT 04 (Sementara)",
      img: "https://i.ibb.co.com/2SLQPW8/IMG-20231208-114325-Agus-Santoso.jpg",
      email: "santosoagusbdg@gmail.com",
      phone: "087736950274",
      group: "Struktural",
      order: 1,
    },
    {
      name: "Ahmad Syafi",
      nickName: "Fei",
      address: "D3 No. 14",
      position: "Humas dan Digitalisasi",
      img: "https://i.ibb.co.com/CBN4pGt/image-1.png",
      email: "syafi’i@gmail.com",
      phone: "081563535112",
      group: "Fungsional (Badan Kelengkapan)",
      order: 2,
    },
    {
      name: "Handika Alfiansyah, S.E.",
      nickName: "Dika",
      address: "B3 No. 09",
      position: "Humas dan Digitalisasi",
      img: "https://i.ibb.co.com/jfphmsP/Screenshot-2025-01-01-10-39-09-589-com-facebook-katana-edit.jpg",
      email: "koboygrind13@gmail.com",
      phone: "082117159783",
      group: "Fungsional (Badan Kelengkapan)",
      order: 2,
    },
    {
      name: "Doddy Novianzi",
      nickName: "Doddy",
      address: "B3 No. 13",
      position: "Keamanan dan Ketertiban",
      img: "https://i.ibb.co.com/ypmNHD5/IMG-20240417-123528-Doddy-Novianzi-suhardiana.jpg",
      email: "doddy@gmail.com",
      phone: "081222251663",
      group: "Fungsional (Badan Kelengkapan)",
      order: 2,
    },
    {
      name: "Yanuar Permana",
      nickName: "Yanuar",
      address: "C1 No. 07",
      position: "Keamanan dan Ketertiban",
      img: "https://i.ibb.co.com/JqhTJFN/IMG-20250101-WA0022.jpg",
      email: "yanuarpermana518@gmail.com",
      phone: "082117638188",
      group: "Fungsional (Badan Kelengkapan)",
      order: 2,
    },
    {
      name: "Didin Saprudin",
      nickName: "Didin",
      address: "E1 No. 4",
      position: "Kebersihan dan Lingkungan Hidup",
      img: "https://i.ibb.co.com/Gkw7Kss/17022171996441815770597606913283-Syafii-Ahmad.jpg",
      email: "didin@gmail.com",
      phone: "0895395937376",
      group: "Fungsional (Badan Kelengkapan)",
      order: 2,
    },
    {
      name: "Sholeh Indra Kusmana",
      nickName: "Sholeh",
      address: "D3 No. 19",
      position: "Bidang Perencanaan",
      img: "https://i.ibb.co.com/gvsd3zk/IMG-20231212-WA0000.jpg",
      email: "sholehindra91@gmail.com",
      phone: "081220245960",
      group: "Fungsional (Badan Kelengkapan)",
      order: 2,
    },
    {
      name: "Indra Mardiansyah",
      nickName: "Indra",
      address: "I2 No. 14",
      position: "Kepemudaan Olahraga dan Kesejahteraan Sosial",
      img: "https://i.ibb.co.com/qymS5ch/Whats-App-Image-2025-01-07-at-6-12-08-AM.jpg",
      email: "oboth.indra@gmail.com",
      phone: "081324026800",
      group: "Fungsional (Badan Kelengkapan)",
      order: 2,
    },
    {
      name: "Mohamad Fahrul Azis, S.M.",
      nickName: "Fahrul",
      address: "D2 No. 03",
      position: "Kepemudaan Olahraga dan Kesejahteraan Sosial",
      img: "https://i.ibb.co.com/YLb3qLM/image-3.png",
      email: "mfahrulazis3@gmail.com",
      phone: "085157569929",
      group: "Fungsional (Badan Kelengkapan)",
      order: 2,
    },
  ],
};
